language: 
  - python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls

before_script:
  - export FLASK_APP='run.py'
  - psql -c 'create database sendit;' -U postgres
  - export DB_URL='postgresql://postgres@localhost:5432/sendit'
  - flask run

script:
 - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls